export const promise = {
  PENDING: '_PENDING',
  REJECTED: '_REJECTED',
  FULFILLED: '_FULFILLED',
};

export const notification = {
  TOGGLE_SNACKBAR: 'TOGGLE_SNACKBAR',
};

export const query = {
  GET_HISTORY: 'GET_QUERY_HISTORY',
  ADD: 'ADD_QUERY',
  DELETE: 'DELETE_QUERY',
  SET_SELECTED: 'SET_SELECTED_QUERY',
};

export const article = {
  GET_ARTICLE: 'GET_ARTICLE',
  TOGGLE_COMPRESSION: 'TOGGLE_COMPRESSION',
};

export const screen = {
  ROOT_SCREEN: 'ROOT_SCREEN',
  LOGIN: 'LOGIN_SCREEN',
  MAIN: 'MAIN_SCREEN',
  QUERY_HISTORY: 'QUERY_HISTORY_SCREEN',
  INTERNET_RESOURCES: 'INTERNET_RESOURCES_SCREEN',
  SOCIAL_RESOURCES: 'SOCIAL_RESOURCES_SCREEN',
  EDITOR: 'EDITOR_SCREEN',
  ARTICLE_LIST: 'ARTICLE_LIST_SCREEN',
  SOURCES_SCREEN: 'ARTICLE_SOURCES_SCREEN',
  ADMIN_SCREEN: 'ADMIN_SCREEN',
};

export const user = {
  GET_USERS: 'GET_ALL_USERS',
  ADD: 'ADD_USER',
  DELETE: 'DELETE_USER',
  UPDATE: 'UPDATE_USER',
  ADMIT_USER: 'ADMIT_USER',
  LOG_OUT: 'LOG_OUT_USER',
};